version: '3.8'
services: 
  nginx:
    image: nginx:1.17.4-alpine
    ports:
      - 8080:80
    depends_on:
      - php
      - db
    volumes:
      - .:/phonestore
      - ./docker/config/default.conf:/etc/nginx/conf.d/default.conf
  php: 
    build: ./docker
    volumes:
      - .:/phonestore
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on: 
      - db
      - redis
    environment:
      - DB_PORT=3306
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASS=123456789
      - DB_NAME=phonestore

  db:
    image: mysql:5.7
    container_name: db
    ports: 
      - "3307:3306"
    volumes: 
      - db_data:/var/lib/mysql
      - ./docker/mysql/phonestore.sql:/docker-entrypoint-initdb.d/phonestore.sql
    environment:
      - MYSQL_DATABASE=phonestore
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_PASSWORD=123456789
    command: --default-authentication-plugin=mysql_native_password

  redis:  
    image: redis:5.0.6-alpine
    ports:
      - "6382:6379"

  phpmyadmin:
    image: phpmyadmin
    ports: 
      - 8090:80
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=123456789

volumes:
  db_data: